version: '3'
services:
  db:
    image: mongo:5.0
    ports: 
      - "27017:27017"
    
  webapp:
    build: ./web-app
    ports:
      - "6001:5000"  # Exposing port 5000 inside the container as 6001 on the host
    depends_on:
      - db

  mlclient:
    build: ./machine-learning-client
    ports:
      - "7001:5000"  # Exposing port 5000 inside the container as 7001 on the host
    depends_on:
      - db