name: Python Test with Coverage in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4

    # Use Docker Compose to build and run the test services
    - name: Run tests with Docker Compose
      run: |
        docker-compose -f docker-compose.yaml up --build test_webapp test_mlclient

    # Shutdown and cleanup
    - name: Shutdown
      run: docker-compose -f docker-compose.yaml down
